# Generated by Django 5.1.4 on 2025-01-04 22:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFluxoDeCaixa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
