# Generated by Django 5.1.4 on 2025-01-05 00:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFluxoDeCaixa', '0003_rename_descricao_receita_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id_despesa', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('conta', models.TextField(max_length=100)),
                ('vencimento', models.DateField(default=django.utils.timezone.now)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.TextField(max_length=100)),
                ('observacao', models.TextField()),
            ],
        ),
    ]
