# Generated by Django 5.1.4 on 2025-01-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFluxoDeCaixa', '0004_despesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='tipo',
            field=models.TextField(default='Crédito', max_length=100),
        ),
    ]
