# Generated by Django 5.1.4 on 2025-01-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id_receita', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('conta', models.TextField(max_length=100)),
                ('descricao', models.TextField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField()),
            ],
        ),
    ]
