# Generated by Django 5.1.4 on 2025-01-04 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFluxoDeCaixa', '0002_alter_receita_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='descricao',
            new_name='categoria',
        ),
    ]
