# Generated by Django 5.1.4 on 2025-01-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFluxoDeCaixa', '0005_despesa_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.TextField(max_length=100)),
                ('tipo_categoria', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id_conta', models.AutoField(primary_key=True, serialize=False)),
                ('conta', models.TextField(max_length=100)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.TextField(max_length=2)),
                ('data_fechamento', models.TextField(max_length=2)),
            ],
        ),
    ]
